# Generated by Django 4.2.4 on 2023-09-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listings",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("userid", models.IntegerField()),
                ("book_title", models.CharField(max_length=100)),
                ("isbn", models.IntegerField()),
                ("genre", models.CharField(max_length=100)),
                ("age_group", models.CharField(max_length=20)),
                ("for_sale", models.BooleanField()),
                ("for_borrowing", models.BooleanField()),
                ("price", models.IntegerField()),
            ],
        ),
    ]
