# Generated by Django 4.2.5 on 2023-09-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='img_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
