# Generated by Django 4.2.5 on 2023-09-06 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_listings_img_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='img_link',
            new_name='imgurl',
        ),
    ]
