# Generated by Django 4.2.5 on 2023-09-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_listings_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='times_viewed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
