# Generated by Django 4.2.5 on 2023-09-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_listings_borrowed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='condition',
            field=models.CharField(default='x', max_length=50),
            preserve_default=False,
        ),
    ]
