# Generated by Django 4.2.5 on 2023-09-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_listings_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='for_borrowing',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='for_sale',
        ),
        migrations.AddField(
            model_name='listings',
            name='saleOrBorrow',
            field=models.CharField(default='Sale', max_length=20),
            preserve_default=False,
        ),
    ]
