# Generated by Django 4.2.5 on 2023-09-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_remove_listings_for_borrowing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cart',
            field=models.JSONField(default={}),
        ),
    ]
